name: quluko_ffmpeg_wrapper
description: A wrapper around FfmpegKit for Quluko app. (using LGPL licensed FFmpeg)
version: 2.0.3
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffmpeg_kit_flutter_new: ^4.5.1  # Latest stable, LGPL by default
